packages:
  - apps/*
  - packages/*
catalog:
  "@base-ui-components/react": ^1.0.0-alpha.5
  "@biomejs/biome": ^1.9.4
  "@phosphor-icons/react": ^2.1.7
  "@sanity/image-url": ^1.1.0
  "@sanity/vision": ^3.72.1
  "@tailwindcss/postcss": ^4.0.3
  "@types/node": ^22.13.0
  "@types/react-dom": ^19.0.3
  "@types/react": ^19.0.8
  clsx: ^2.1.1
  groqd: ^1.0.4
  next-sanity: ^9.8.47
  next: ^15.1.6
  postcss: ^8.5.1
  react-dom: ^19.0.0
  react: ^19.0.0
  sanity: ^3.72.1
  tailwind-merge: ^3.0.1
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^4.0.3
  taze: ^18.3.0
  turbo: ^2.4.0
  typescript: ^5.7.3
  zod: ^3.24.1
