packages:
  - apps/*
catalog:
  '@biomejs/biome': ^1.9.4
  '@tailwindcss/postcss': ^4.0.3
  '@types/node': ^22.13.0
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  next: ^15.1.6
  postcss: ^8.5.1
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwindcss: ^4.0.3
  taze: ^18.3.0
  turbo: ^2.4.0
  typescript: ^5.7.3
