packages:
  - apps/*
  - packages/*
catalog:
  "@base-ui-components/react": ^1.0.0-alpha.6
  "@biomejs/biome": ^1.9.4
  "@faker-js/faker": ^9.5.0
  "@phosphor-icons/react": ^2.1.7
  "@sanity/image-url": ^1.1.0
  "@sanity/vision": ^3.75.1
  "@tailwindcss/postcss": ^4.0.6
  "@tailwindcss/vite": ^4.0.6
  "@tanstack/react-router": ^1.105.0
  "@tanstack/router-devtools": ^1.105.0
  "@tanstack/router-plugin": ^1.105.0
  "@types/node": ^22.13.4
  "@types/react-dom": ^19.0.3
  "@types/react": ^19.0.9
  "@vitejs/plugin-react-swc": ^3.8.0
  "@vitest/coverage-v8": ^3.0.5
  "@vitest/ui": ^3.0.5
  clsx: ^2.1.1
  groqd: ^1.0.9
  msw: ^2.7.0
  next-sanity: ^9.8.57
  next: ^15.1.7
  postcss: ^8.5.2
  react-dom: ^19.0.0
  react: ^19.0.0
  sanity: ^3.75.1
  tailwind-merge: ^3.0.1
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^4.0.6
  taze: ^18.5.0
  turbo: ^2.4.2
  typescript: ^5.7.3
  vite-tsconfig-paths: ^5.1.4
  vite: ^6.1.0
  vitest: ^3.0.5
  zod: ^3.24.2
