packages:
  - apps/*
  - packages/*
catalog:
  "@base-ui-components/react": ^1.0.0-alpha.6
  "@biomejs/biome": ^1.9.4
  "@phosphor-icons/react": ^2.1.7
  "@sanity/image-url": ^1.1.0
  "@sanity/vision": ^3.74.1
  "@tailwindcss/postcss": ^4.0.5
  "@tailwindcss/vite": ^4.0.5
  "@tanstack/react-router": ^1.101.2
  "@tanstack/router-devtools": ^1.101.2
  "@tanstack/router-plugin": ^1.101.2
  "@types/node": ^22.13.1
  "@types/react-dom": ^19.0.3
  "@types/react": ^19.0.8
  "@vitejs/plugin-react-swc": ^3.8.0
  clsx: ^2.1.1
  groqd: ^1.0.6
  next-sanity: ^9.8.54
  next: ^15.1.6
  postcss: ^8.5.1
  react-dom: ^19.0.0
  react: ^19.0.0
  sanity: ^3.74.1
  tailwind-merge: ^3.0.1
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^4.0.5
  taze: ^18.4.0
  turbo: ^2.4.0
  typescript: ^5.7.3
  vite-tsconfig-paths: ^5.1.4
  vite: ^6.1.0
  zod: ^3.24.1
